remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Sign in with Kingdom Hall Attendant API
description: API de autenticación de Kingdom Hall Attendant para gestionar el inicio de sesión y el registro de usuarios en aplicaciones que utilizan el ecosistema de KHA.
